services:
  - type: web
    name: vigili-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_semplice.py
    envVars:
      - key: BOT_TOKEN
        value: "7554833400:AAEQzzpJESp_FNqd-nPLZh1QNlUoF9_bGMU"
      - key: GITHUB_TOKEN
        value: "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"
    autoDeploy: false
