name: Monthly Redeploy
on:
  schedule:
    - cron: '0 6 1 * *'  # 1° del mese alle 6:00
  workflow_dispatch:      # Manuale

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Redeploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"
