name: Redeploy Controller
on:
  schedule:
    - cron: '0 0 1 * *'  # Prima di ogni mese a mezzanotte
  workflow_dispatch:
    inputs:
      force-redeploy:
        description: 'Forza il re-deploy ignorando le impostazioni'
        required: false
        default: 'false'

jobs:
  control-redeploy:
    runs-on: ubuntu-latest
    outputs:
      should_redeploy: ${{ steps.decision.outputs.redeploy }}
    steps:
      - name: Check current month
        id: month_check
        run: |
          CURRENT_MONTH=$(date +"%m")
          LAST_REDEPLOY_MONTH="${{ secrets.LAST_REDEPLOY_MONTH }}"
          
          if [ "$CURRENT_MONTH" != "$LAST_REDEPLOY_MONTH" ]; then
            echo "🔄 Mese cambiato, re-deploy necessario"
            echo "should_redeploy=true" >> $GITHUB_OUTPUT
          else
            echo "✅ Re-deploy già eseguito questo mese"
            echo "should_redeploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Force redeploy check
        if: github.event.inputs.force-redeploy == 'true'
        id: force_check
        run: echo "should_redeploy=true" >> $GITHUB_OUTPUT

      - name: Final decision
        id: decision
        run: |
          if [ "${{ steps.month_check.outputs.should_redeploy }}" = "true" ] || [ "${{ steps.force_check.outputs.should_redeploy }}" = "true" ]; then
            echo "🎯 Decisione: Esegui re-deploy"
            echo "redeploy=true" >> $GITHUB_OUTPUT
          else
            echo "🎯 Decisione: Salta re-deploy"
            echo "redeploy=false" >> $GITHUB_OUTPUT
          fi

  execute-redeploy:
    needs: control-redeploy
    if: needs.control-redeploy.outputs.should_redeploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger redeploy
        uses: johnbeynon/redeploy-action@v1.1.0
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      - name: Update last redeploy month
        run: |
          CURRENT_MONTH=$(date +"%m")
          echo "CURRENT_MONTH=$CURRENT_MONTH" >> $GITHUB_ENV
        # Nota: Aggiornamento del secret va fatto manualmente o via API

  skip-redeploy:
    needs: control-redeploy
    if: needs.control-redeploy.outputs.should_redeploy == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip notification
        run: |
          echo "⏸️ Re-deploy automatico saltato per questo mese"
          echo "Per forzare il re-deploy, esegui manualmente il workflow"
